### ISSUE TITLE
Latest version fail with: BWIPJS.load is not a function

### ISSUE THREAD

**Issue by nandub** [epha/rescode#7]
```
/usr/local/lib/node_modules/rescode/lib/bwipp/ean13.js:14
if (!BWIPJS.bwipp["ean2"]) BWIPJS.load("bwipp/ean2.js");
                                  ^

TypeError: BWIPJS.load is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/rescode/lib/bwipp/ean13.js:14:35)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.exports.addExport (/usr/local/lib/node_modules/rescode/lib/bwipp/index.js:23:2)
    at /usr/local/lib/node_modules/rescode/lib/codes.js:16:11
```

**Comment by nandub** [comment]
Never mind, you must use this to work:

```
codes.loadModules(["ean2", "ean5", "ean8", "ean13"]);
```

I was setting it like this:

```
codes.loadModules(["ean13"]);
```
